---
- name: Ensure UFW is installed
  package:
    name: ufw
    state: present

- name: Allow SSH access from internal networks
  ufw:
    rule: allow
    port: '22'
    proto: tcp
    src: '{{ item }}'
  with_items:
    - <REDACTED>/24
    - <REDACTED>/24

- name: Enable UFW logging
  ufw:
    logging: 'True'

- name: Enable UFW
  ufw:
    state: enabled
